#theme = "onedark"
theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
scroll-lines = 3
auto-completion = true
completion-trigger-len = 2
auto-info = true
true-color = true
color-modes = true


[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "diagnostics"]
center = ["file-name"]
right = [
    "selections",
    "file-type",
    "file-encoding",
    "position-percentage",
    "position",
]

[editor.file-picker]
hidden = true
ignore = true
parents = true
git-ignore = true


[editor.search]
smart-case = true
wrap-around = true

[keys.normal]
X = "extend_line_above"
D = "delete_char_backward"
